version: '3.7'
services:
  database:
    restart: always
    image: mysql:latest
    volumes:
      - ./storage/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  server:
    image: gifwall
    environment:
      - MAKE_DATABASE=true
      - DATABASE_HOST=database
      - AUTH_PASS=jifWall
    volumes:
      - ./storage/file_store:/file_store
    ports:
      - 80:80
      - 8080:8080
